name: Auto release
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
      steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Step 2 - Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Step 3 - Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Step 4 - Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
          VERSION: "v${{ steps.gitversion.outputs.semVer }}"
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }} ${{ env.TITLE }}
          body: ${{ env.BODY }}
          draft: false
          prerelease: false
